### ISSUE TITLE
Support dropdown list along with the autocomplete

### ISSUE THREAD

**Issue by pjesi** [jamieholst/selectToAutocomplete#1]
It would be nice if the plugin had an option to include a button to open available options. It could be positioned on the far right in the search box and when clicked, it would open a list of the predefined options. This would cover cases where the user didn't know about the options available.

**Comment by jamieholst** [comment]
Like the idea.

Although this would seem more related to the autocomplete plugin of choice. Actually, jQuery UI has an example of a combobox which does exactly what you describe:

http://jqueryui.com/demos/autocomplete/#combobox

Maybe one could investigate making an adapter for this?

**Comment by pjesi** [comment]
The default adapter could use the existing select-element right? Like the select box for countries.

**Comment by jakemac53** [comment]
I was wondering about this same thing. I currently use Chosen http://harvesthq.github.com/chosen/ and what it does is as soon as you click in the box all the options appear below it. I think this should do the same thing, as soon as you click it should just show you all the options, and then as you type it will filter them down as it usually would. Would be a very simple solution.

**Comment by jamieholst** [comment]
In general, I'm still not sure this belongs in the selectToAutocomplete plugin, it still seems more like an Autocomplete plugin feature. 

However, since a couple of other obvious features also belong in an Autocomplete plugin, I'm thinking of writing one (or adapting an existing) which includes these features. Or perhaps adapting the plugin that jakemac53 links to. 

Let's keep this issue open for now and see if other people want this feature too. 

@pjesi
You can overwrite the way the select field is handled during initialization by passing in a 'handle_select_field' function that accepts a value, $select_field. 

Currently, the select field is simply hidden, but the value still change and it is actually the value of this field that is sent to the server when the form is submitted. 

So yes, you could keep it displayed and allow the user to interact with either field.

@jakemac53
That's a very neat plugin.

**Comment by littlefyr** [comment]
Its worth noting that if you just start pressing the down button, you'll get the same result, although why lesotho appears first is beyond me.

**Comment by jaystarkey** [comment]
@JamieAppleseed 
I would like to see integration with chosen referenced by @jakemac53, too; I actually think the control as is confuses users as much as it helps because they don't know what to expect.  They are familiar with a dropdown, though, and the search is function of your control is amazing.  If they could have the choice of typing or selecting, that would be the best of both worlds, I guess with the booster values determining the order of the dropdown, and then alphabetical for list items without any boosting? 

I too noticed the problem with lesotho showing up first, and interestingly Åland Islands shows up in the L's.  It is like they are switching places.  Just to see what happened, I deleted the Aland Islands and then a different A showed up in the L's.  Odd ordering behavior indeed.

By the way, you should add にほん to Japan's alternative spellings, because then it will match as users type in hiragana before they convert the whole string it into kanji. ;-)
