### ISSUE TITLE
Add LICENSE.txt to root of project

### ISSUE THREAD

**Issue by greggles** [jamieholst/selectToAutocomplete#31]
I suggest choosing to multi-license under a broad set:
- GPLv2 and later
- MIT

maybe some others?

**Comment by dontangg** [comment]
The code is currently under the MIT license.  You can see that by going to the [homepage](http://baymard.com/labs/country-selector) and clicking on "Download & License".  I'm sure Jamie will chime in on your suggestion.  I just thought I'd respond to your question with what I knew.

**Comment by jamieholst** [comment]
The license is also at the top of the plugin code itself:

https://github.com/JamieAppleseed/selectToAutocomplete/blob/master/jquery.select-to-autocomplete.js

We developed the plugin as a proof-of-concept and it turned out to work quite well so we decided to share it with the community.  

I wish for the code to be absolutely free for everyone to use in whatever way they please. I believe the current license prescribe this freedom but if that is not the case then I wholeheartedly agree that another license which do reflect this should be used instead.

**Comment by greggles** [comment]
Great to know it's MIT (or less ambiguously, the MIT-Expat license http://www.gnu.org/licenses/license-list.html#Expat ).

I've updated the title to be more clear in the request: to add a LICENSE.txt in the root of the project, which is pretty standard and makes it easy to identify what's going on.

Thanks for sharing the code and choosing a liberal license!
