### ISSUE TITLE
Should boost beginning of word partial matches over inner-word matches

### ISSUE THREAD

**Issue by jcoyne** [jamieholst/selectToAutocomplete#6]
Typing in "Sw" currently gives botswana a favorable ranking over Sweden.

**Comment by jcoyne** [comment]
Similarly "Indi" favors "British Indian Ocean Territory" over "India"

**Comment by jamieholst** [comment]
Completely agree. This is probably the single most important feature, but unfortunately this requires actual relevance sorting of the matches – something which isn't easily done in pure front-end code.

Currently, a one-time filtering is performed at initialization if 'sorting' is enabled. However, after this, the plugin only filters the results as you type. 

Another downside is that this functionality would seem more appropriate to have in the Autocomplete plugin rather than this selectToAutocomplete plugin. 

I'll see if I can add this for the jQuery UI adapter.

**Comment by jamieholst** [comment]
Hi jcoyne,

I've added this functionality in commit [7b7fd063b6ac68669ceb6e84581292be87922ff3](https://github.com/JamieAppleseed/selectToAutocomplete/commit/7b7fd063b6ac68669ceb6e84581292be87922ff3).

**Comment by jcoyne** [comment]
Excellent.  Great work!

-Justin

On Sun, Nov 13, 2011 at 11:28 AM, Jamie Appleseed
reply@reply.github.com
wrote:

**Comment by jamieholst** [comment]
Cheers! It really is so much better this way. 

Thanks for the feedback – much appreciated.
