### ISSUE TITLE
Registar onChange event 

### ISSUE THREAD

**Issue by adardesign** [jamieholst/selectToAutocomplete#66]
Is there a hook in the call to register events `onChange` or `onSelect`?

I save the data in `localStorage`  after each change

Like this

```
selectToAutocomplete({
                autoFocus: false,
                autoselect: false,
                onChange: fn

            })
```

**Comment by jamieholst** [comment]
You can simply bind to the respective DOM elements used by the plugin – namely the text field and select tag (hidden but still available on the page).

For change events you'd likely want to bind to the select tag, which should be very easy since you already have to select that to initialize the selectToAutocomplete plugin. 

Something like this:

```
$('select')
  .selectToAutocomplete()
  .change(function(e){
    alert($(this).val());
  });
```
